name: basic
dependencies:
  - python==3.9.5
  - invoke==1.6.1
  - jupyterlab==3.3.0
  - scipy==1.8.0
  - pandas==1.4.1
  - matplotlib==3.5.1
  - seaborn==0.11.2
  - scikit-learn==1.0.2
  - statsmodels==0.13.2
  - pip:
    - xlrd==2.0.1 # pd.read_excel
    - PyYAML==6.0
    - missingno==0.4.2
    - xgboost==1.5.2 
