name: crawling
dependencies:
  - python==3.7.0
  - jupyter
  - scipy==1.1.0
  - pandas==0.23.4
  - numpy==1.15.1
  - click
  - scrapy
  - beautifulsoup4
  - requests
  #- spyder-kernels
  - pip:
    - PyYAML
    - newspaper3k 
