name: analysis
dependencies:
  - python==3.9
  - jupyterlab==3.2.9
  - invoke==1.6.0 # make functionality with python
  - click==8.0.3 # customized prints
  - scikit-learn==1.0.2
  - statsmodels==0.12.2
  - pandas==1.4.1
  - matplotlib==3.5.1
  - seaborn==0.11.2
  #- spyder-kernels==2.0.1
  - pip
  - pip:
    - xlrd==2.0.1 # pd.read_excel
    - dataprep==0.4.2 # data preparation with good EDA
    - missingno==0.4.2 # missing values
    - hiplot==0.1.32 # parallel plot
    - featexp==0.0.7 # features analysis
    - xgboost==1.5.2
    - minepy==1.0.0 # non-linear correlation test
